version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
       MYSQL_DATABASE: 'certmanv2'
       MYSQL_USER: 'eagle'
       MYSQL_PASSWORD: 'r00t123'
       MYSQL_ROOT_PASSWORD: 'r00t123'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/appdata/projects/dashboard
    ports:
      - "8000:8000"
    depends_on:
      - db
  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/appdata/projects/dashboard
    links:
      - db
    depends_on:
      - db



