# Generated by Django 2.1.7 on 2019-03-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_status', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_hostname', models.CharField(max_length=255)),
                ('cert_scan_port', models.CharField(max_length=255)),
                ('cert_app_owner', models.CharField(max_length=255)),
                ('cert_platform', models.CharField(max_length=255)),
                ('cert_issuer', models.CharField(max_length=255)),
                ('cert_cn', models.CharField(max_length=255)),
                ('cert_days', models.IntegerField()),
                ('cert_date', models.DateField()),
                ('cert_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certman.CertId')),
                ('cert_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certman.CertStatus')),
                ('cert_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certman.CertType')),
                ('control_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certman.ControlType')),
            ],
        ),
    ]
