# Generated by Django 2.1.7 on 2019-03-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certid',
            old_name='cert_status',
            new_name='cert_id',
        ),
        migrations.RenameField(
            model_name='certstatus',
            old_name='cert_id',
            new_name='cert_status',
        ),
    ]
