# Generated by Django 2.1.7 on 2019-03-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certman', '0002_auto_20190321_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='control_name',
            new_name='control_type',
        ),
    ]
