# Generated by Django 2.1.7 on 2019-06-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certman', '0003_auto_20190321_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_scan_range', models.CharField(max_length=255)),
                ('cert_port_range', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Add Network/Port',
                'verbose_name_plural': 'Add Network/Port',
            },
        ),
        migrations.CreateModel(
            name='CertScanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_hostname', models.CharField(max_length=255)),
                ('cert_service', models.CharField(max_length=255)),
                ('cert_platform', models.CharField(max_length=255)),
                ('cert_data', models.TextField()),
            ],
            options={
                'verbose_name': 'Add Certificate File',
                'verbose_name_plural': 'Add Certificate File',
            },
        ),
        migrations.CreateModel(
            name='CertScanUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_hostname', models.CharField(max_length=255)),
                ('cert_port', models.IntegerField()),
                ('cert_service', models.CharField(max_length=255)),
                ('cert_platform', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Add URL',
                'verbose_name_plural': 'Add URL',
            },
        ),
        migrations.RenameModel(
            old_name='ControlType',
            new_name='CertControl',
        ),
        migrations.RenameModel(
            old_name='Record',
            new_name='CertScanRecord',
        ),
        migrations.AlterModelOptions(
            name='certcontrol',
            options={'verbose_name': 'Define Control Type', 'verbose_name_plural': 'Define Control Type'},
        ),
        migrations.AlterModelOptions(
            name='certid',
            options={'verbose_name': 'Define Certificate ID', 'verbose_name_plural': 'Define Certificate ID'},
        ),
        migrations.AlterModelOptions(
            name='certscanrecord',
            options={'verbose_name': 'Show Scan Result', 'verbose_name_plural': 'Show Scan Result'},
        ),
        migrations.AlterModelOptions(
            name='certstatus',
            options={'verbose_name': 'Define  Status', 'verbose_name_plural': 'Define  Status'},
        ),
        migrations.AlterModelOptions(
            name='certtype',
            options={'verbose_name': 'Define Certificate Type', 'verbose_name_plural': 'Define Certificate Type'},
        ),
        migrations.RenameField(
            model_name='certcontrol',
            old_name='control_name',
            new_name='cert_control',
        ),
        migrations.AddField(
            model_name='certscanurl',
            name='cert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certman.CertId'),
        ),
        migrations.AddField(
            model_name='certscanfile',
            name='cert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certman.CertId'),
        ),
    ]
